'''unidades.py'''

UNIDADES = [
  {
    "id": "sede",
    "nome": "Santa Casa — Sede / Administração",
    "endereco": "Rua Padre Bronislau Chereck, 15",
    "bairro": "Centro",
    "telefone": "(12) 3896-1710",
    "categoria": "sede",
    "latitude": -23.7780,
    "longitude": -45.3582,
  },
  {
    "id": "hospital",
    "nome": "Hospital Municipal Gov. Mário Covas",
    "endereco": "Av. Prof. Malaquias de Oliveira Freitas, 154",
    "bairro": "Barra Velha",
    "telefone": "(12) 3895-3520",
    "categoria": "hospital",
    "latitude": -23.8052,
    "longitude": -45.3620,
  },
  {
    "id": "ubs_barra_velha",
    "nome": "UBS Barra Velha",
    "endereco": "Rua Benedito dos Anjos Sampaio, 225",
    "bairro": "Barra Velha",
    "telefone": "(12) 3895-7190",
    "categoria": "ubs",
    "latitude": -23.8040,
    "longitude": -45.3615,
  },
  {
    "id": "ubs_alto_barra",
    "nome": "UBS Alto da Barra",
    "endereco": "Rua dos Carijos, 550",
    "bairro": "Zabumba",
    "telefone": "(12) 3896-9200",
    "categoria": "ubs",
    "latitude": -23.8090,
    "longitude": -45.3650,
  },
  {
    "id": "ubs_agua_branca",
    "nome": "UBS Água Branca",
    "endereco": "Av. Coronel Vicente Daria Lima, 1435",
    "bairro": "Água Branca",
    "telefone": "(12) 3896-6530",
    "categoria": "ubs",
    "latitude": -23.7920,
    "longitude": -45.3540,
  },
  {
    "id": "ubs_itaquanduba",
    "nome": "UBS Itaquanduba",
    "endereco": "Av. dos Bandeirantes, 230",
    "bairro": "Itaquanduba",
    "telefone": "(12) 3896-9200",
    "categoria": "ubs",
    "latitude": -23.7700,
    "longitude": -45.3490,
  },
  {
    "id": "ubs_pereque",
    "nome": "UBS Perequê",
    "endereco": "Rua do Quilombo, 73",
    "bairro": "Perequê",
    "telefone": "(12) 2896-9200",
    "categoria": "ubs",
    "latitude": -23.7610,
    "longitude": -45.3460,
  },
  {
    "id": "ubs_costa_norte",
    "nome": "UBS Costa Norte",
    "endereco": "Av. Leonardo Reale, 4080",
    "bairro": "Ponta Azeda",
    "telefone": "(12) 3896-1371",
    "categoria": "ubs",
    "latitude": -23.7200,
    "longitude": -45.3250,
  },
  {
    "id": "ubs_costa_sul",
    "nome": "UBS Costa Sul",
    "endereco": "Av. Riachuelo, 6311",
    "bairro": "Praia Grande",
    "categoria": "ubs",
    "latitude": -23.8350,
    "longitude": -45.3700,
  },
  {
    "id": "centro_saude_iii",
    "nome": "Centro de Saúde III",
    "endereco": "Rua São Benedito, 151",
    "bairro": "Centro",
    "telefone": "(12) 3896-1212",
    "categoria": "especialidade",
    "latitude": -23.7795,
    "longitude": -45.3565,
  },
  {
    "id": "centro_especialidades",
    "nome": "Centro de Especialidades",
    "endereco": "Rua Padre Bronislau Cherek, 15",
    "bairro": "Centro",
    "telefone": "(12) 3896-3400",
    "categoria": "especialidade",
    "latitude": -23.7783,
    "longitude": -45.3580,
  },
  {
    "id": "centro_julia_tenorio",
    "nome": "Centro Especializado Júlia Tenório",
    "endereco": "Av. Princesa Isabel, 1673",
    "bairro": "Centro",
    "telefone": "(12) 3896-1500",
    "categoria": "especialidade",
    "latitude": -23.7760,
    "longitude": -45.3600,
  },
  {
    "id": "ciama",
    "nome": "CIAMA",
    "endereco": "Rua Carolina Vanderstappen, 275",
    "bairro": "Perequê",
    "telefone": "(12) 3896-1535",
    "categoria": "especialidade",
    "latitude": -23.7625,
    "longitude": -45.3450,
  },
]
